---

- name: My first playbook
  hosts: all
  gather_facts: false
  become: true
  vars:
    # Число проходов при очистке освобождаемых блоков файловой системы
    passes: 1
    # Флаги аудита успехов и отказов
    events: "ocxuew:ocxuew"
    # Список создаваемых групп пользователей
    special_groups:
      - operators
      - nachsmens
      - technics
  vars_prompt:
    # Пароль создаваемых пользователей
    - name: default_passwd
      prompt: USERS  password

  tasks:
  - name: Получение имени учетной записи администратора безопасности
    shell: id -n -u 1000
    register: admin_name
    # имя учетной записи в {{ admin_name.stdout }}

  - name: Генерация ssh-ключей администратора безопасности
    shell: |
      mkdir -p /home/{{ admin_name.stdout }}/.ssh
      ssh-keygen -f /home/{{ admin_name.stdout }}/.ssh/id_rsa -q -N "" <<< y
      chown -R {{ admin_name.stdout }}:{{ admin_name.stdout }} /home/{{ admin_name.stdout }}/.ssh
    # The warn parameter for shell was deprecated in Ansible 2.11 and removed in Ansible 2.14. 
    # args:
      # warn: false

  - name: Включение политик безопасности
    shell:
      "{{ item }} enable" 
    loop:
      - astra-swapwiper-control
      - astra-interpreters-lock
      - astra-sysrq-lock
      - astra-ptrace-lock
      - astra-commands-lock
      - astra-macros-lock
      - astra-sudo-control
      - astra-nobootmenu-control

  - name: Включение и настройка гарантированного удаления файлов и папок
    shell: |
      astra-secdel-control enable
      sed -i 's/secdel[^ ]*/secdelrnd={{ passes }}/g' /etc/fstab
    when: passes > 0

  - name: Выключение гарантированного удаления файлов и папок
    shell:
      astra-secdel-control disable
    when: passes == 0
     
  - name: Настройка политики блокировки учетных записей
    shell:
      sed -i 's/pam_tally.so.*/pam_tally.so deny=6 unlock_time=1800/' /etc/pam.d/common-auth
  # args:
  #   warn: false

  - name: Настройка политики паролей
    shell: |
      # Настройка сложности (длины и алфавита) паролей
      sed -i 's/pam_cracklib.so.*/pam_cracklib.so retry=3 difok=3 minlen=8 lcredit=-1 ucredit=-1 dcredit=-1 ocredit=0/' /etc/pam.d/common-password
      # Настройка максимального количества дней между сменами пароля
      sed -i 's/^PASS_MAX_DAYS.*/PASS_MAX_DAYS 90/' /etc/login.defs
  # args:
  #   warn: false

  - name: Настройка правил протоколирования для пользователей
    shell:
      useraud -mo {{ events }}

  - name: Настройка разрешения удаленного запуска графических приложений
    shell: |
      # Найти в любом месте строки (.*) X11Forwarding, за ним пробел (\s) и любое кол-во произвольных символов (.*)
      sed -i 's/.*X11Forwarding\s.*/X11Forwarding yes/' /etc/ssh/sshd_config
      sed -i 's/.*X11UseLocalhost\s.*/X11UseLocalhost no/' /etc/ssh/sshd_config
  # args:
  #   warn: false

  - name: Создание групп пользователей
    group:
      name: "{{ item }}"
      state: present
    loop: "{{ special_groups }}"

  - name: Извлечение новых файлов из архива
    unarchive:
      src: postinst.tar.gz
      dest: /  

  - name: Включение службы контроля целостности afick
    systemd:
      name: afick
      enabled: true
      masked: no
      daemon_reload: true
      
  - name: Создание символических ссылок на скрипт добавления специальных пользователей
    file:
      src: /usr/local/bin/adduser 
      dest: /usr/bin/{{ item }}
      state: link
    loop:
      - addoperator
      - addnachsmen
      - addadmsec

  - name: Создание учетных записей оператора и начальника смены
    shell: |
      addoperator operator {{ default_passwd }}
      addnachsmen nachsmen {{ default_passwd }}
  # args:
  #   warn: false
  
# Запрет установки бита исполнения не дает выполнять плейбуки, т.к. на удаленных хостах видимо создаются исполняемые скрипты
# Без запрета установки бита исполнениявключение блокировки интерпретаторов также не имеет смысла,
# поэтому как вариант решения, делать эту настройку самой последней
# - name: Настройка запрета установки бита исполнения для всех пользователей, включая администраторов
#   shell:
#     astra-nochmodx-lock enable
  
