---

- name: Astra playbook
  hosts: all
  gather_facts: false
  become: true
  vars:
    # Число неуспешных попыток аутентификации до блокировки учетной записи
    ATTEMPTS_BEFORE_BLOCKING: 6
    # Период разблокирования учетной записи, сек
    UNLOCK_TIME: 1800
    # Число проходов при очистке освобождаемых блоков файловой системы
    SECDELRND_PASSES: 1
    # Максимальное число дней между сменами пароля
    PASS_MAX_DAYS: 90
    # Флаги аудита успехов и отказов
    AUD_FLAGS: "ocxuew:ocxuew"
    # Список создаваемых групп пользователей
    SPECIAL_GROUPS:
      - operators
      - nachsmens
      - technics
  vars_prompt:
    # Пароль создаваемых пользователей
    - name: default_passwd
      prompt: USERS  password

  tasks:
  - name: Получение имени учетной записи администратора безопасности
    ansible.builtin.shell:
      id -n -u 1000
    register: admin_name
    # имя учетной записи в {{ admin_name.stdout }}

  - name: Включение политик безопасности
    ansible.builtin.shell:
      "{{ item }} enable" 
    loop:
      - astra-swapwiper-control
      - astra-interpreters-lock
      - astra-sysrq-lock
      - astra-ptrace-lock
      - astra-commands-lock
      - astra-macros-lock
      - astra-sudo-control
      - astra-nobootmenu-control

  - name: Включение и настройка гарантированного удаления файлов и папок
    ansible.builtin.shell: |
      astra-secdel-control enable
      sed -i 's/secdel[^ ]*/secdelrnd={{ SECDELRND_PASSES }}/g' /etc/fstab
    when: SECDELRND_PASSES > 0

  - name: Выключение гарантированного удаления файлов и папок
    ansible.builtin.shell:
      astra-secdel-control disable
    when: SECDELRND_PASSES == 0

  - name: Настройка политики блокировки учетных записей
    ansible.builtin.replace:
      path: /etc/pam.d/common-auth
      regexp: 'pam_tally.so.*'
      replace: 'pam_tally.so deny={{ ATTEMPTS_BEFORE_BLOCKING }} unlock_time={{ UNLOCK_TIME }}'

  - name: Настройка сложности (длины и алфавита) паролей
    ansible.builtin.replace:
      path: /etc/pam.d/common-password
      regexp: 'pam_cracklib.so.*'
      replace: 'pam_cracklib.so retry=3 difok=3 minlen=8 lcredit=-1 ucredit=-1 dcredit=-1 ocredit=0'
  
  - name: Настройка максимального числа дней между сменами пароля
    ansible.builtin.lineinfile:
      path: /etc/login.defs
      regexp: ^#?PASS_MAX_DAYS
      line: PASS_MAX_DAYS {{ PASS_MAX_DAYS }}

  - name: Настройка правил протоколирования для пользователей
    ansible.builtin.shell:
      useraud -mo {{ AUD_FLAGS }}

  - name: Настройка разрешения удаленного запуска графических приложений
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      line: "{{ item.line }}"
      regexp: "{{ item.regexp }}"
    loop:
      - line: X11Forwarding yes
        regexp: ^X11Forwarding
      - line: X11UseLocalhost no
        regexp: ^X11UseLocalhost

  - name: Настройка формата представления даты и времени в логах syslog-ng
    # Добавить в группу параметров options параметр ts-format(iso);
    ansible.builtin.replace:
      path: /etc/syslog-ng/syslog-ng.conf
      # Вставить после первой группы параметр ts-format(iso)
      regexp: '(^options[\s\S]*?)( ts-format\(iso\);\n};|\n};)'
      replace: '\1 ts-format(iso);\n};'

  - name: Настройка пути к классам обработчиков событий syslog-ng
    ansible.builtin.lineinfile:
      path: /etc/default/syslog-ng
      line: PYTHONPATH="/usr/local/lib/python2.7/dist-packages"
      insertafter: EOF
   
  # Удалить (переименовать) /etc/audit/rules.d/10-parsec.rules, задающий для всех событий ключ parsec-p,
  # после чего их невозможно фильтровать по собственным ключам
  - name: Изменение настроек auditd
    ansible.builtin.shell: |
      if [ -f /etc/audit/rules.d/10-parsec.rules ]; then
        mv /etc/audit/rules.d/10-parsec.rules /etc/audit/rules.d/10-parsec.rules.bak;
      fi

  - name: Извлечение новых файлов из архива
    ansible.builtin.unarchive:
      src: postinst.tar.gz
      dest: /  

  - name: Включение службы контроля целостности afick
    ansible.builtin.systemd:
      name: afick
      enabled: true
      masked: no
      daemon_reload: true
      
  - name: Создание символических ссылок на скрипт добавления специальных пользователей
    ansible.builtin.file:
      src: /usr/local/bin/adduser 
      dest: /usr/bin/{{ item }}
      state: link
    loop:
      - addoperator
      - addnachsmen
      - addadmsec

  - name: Создание групп операторов и начальников смен
    ansible.builtin.group:
      name: "{{ item }}"
      state: present
    loop: "{{ SPECIAL_GROUPS }}"

  - name: Создание учетных записей оператора и начальника смены
    tags: addusers
    ansible.builtin.shell: |
      addoperator operator {{ default_passwd }}
      addnachsmen nachsmen {{ default_passwd }}
  # args:
  #   warn: false

  # Запрет установки бита исполнения не дает выполнять плейбуки, т.к. на удаленных хостах создаются исполняемые скрипты
  # Можно делать эту настройку самой последней, но после этого использование ansible становится невозможным
  # - name: Настройка запрета установки бита исполнения для всех пользователей, включая администраторов
  #   shell:
  #     astra-nochmodx-lock enable
  
