# Именованный канал для отправки уведомлений о системных событиях
# Создается автоматически syslog-ng, но если до запуска программы отображения уведомлений
# ни одного уведомления нет, то канал не создан и программа завершается с ошибкой
p /tmp/syslog-ng.msg 0644 root root
