# Флаг no-parse обязателен, иначе syslog-ng пытается парсить входящее сообщение,
# а оно в собственном формате, в результате в $MESSAGE получается искаженное сообщение
source s_udp_syslog {
    udp(
        port(514)
        flags(no-parse)
    );
};

# В этой точке назначения на всех хостах указывается ip-адрес АРМ АБИ
# сюда отправляются разобранные логи для вывода их в уведомлении
destination d_udp_syslog {
    udp(
        "192.168.56.128"
        port(514)
        template("$notification\n")
    );
};

# Отправка сообщения в именованный канал
destination d_pipe_sender {
    pipe(
        "/tmp/syslog-ng.msg"
        template("$MESSAGE\n")
        persist-name("d_remote_pipe")
    );
};

# Отправка широковещательных уведомлений с помошью программмы gdbus, обернутой питоновским классом
destination d_gdbus_sender {
    python(
        class("custom_syslog_ng_classes.GdbusSender")
    );
};

# Отправка широковещательных уведомлений через питоновскую программу, использующую модуль dbus
destination d_dbus_sender {
    program(
        "/usr/local/bin/dbus-sender"
        template("$MESSAGE\n")
        persist-name("d_dbus_sender")
    );
};

log {
    source(s_udp_syslog);
    destination(d_pipe_sender);
};
