# В источнике ip(0.0.0.0) указывать не нужно,
# иначе возникают непредсказуемые ошибки при запуске syslog-ng
source s_udp_syslog {
    udp(
        port(514)
        flags(no-parse)
    );
};

destination d_udp_syslog {
    udp(
        "192.168.56.128"
        port(514)
        template("$notification\n")
    );
};

destination d_pipe_sender {
    pipe(
        "/tmp/syslog-ng.msg"
        template("$MESSAGE\n")
        persist-name("d_remote_pipe")
    );
};

log {
    source(s_udp_syslog);
    destination(d_pipe_sender);
};
