source s_audit_log {
    # Параметр persist-name нужен т.к. указанный файл уже является источником событий
    file(
        "/var/log/audit/audit.log"
        persist-name("s_audit_log")
        flags(no-parse)
    );
};

destination d_audit_msg_file {
    # Если обработка лога не нужна, можно сразу отправлять лог в файл,
    # в т.ч. именованный канал xmpp-sender
    file(
        "/var/log/audit/audit.msg"
        template("$MESSAGE\n")
    );
};

destination d_audit_parser {
    program(
        "/usr/local/bin/audit-parser"
        template("$MESSAGE\n")
    );
};

filter f_all_critical_events {
    match("passwd_modification", value("MESSAGE")) or
    match("group_modification", value("MESSAGE")) or
    match("user_modification", value("MESSAGE")) or
    match("switching_accounts", value("MESSAGE")) or
    match("pam_modification", value("MESSAGE")) or
    match("systemd_modification", value("MESSAGE")) or
    match("systemd_tools_usage", value("MESSAGE"))
};

log {
    source(s_audit_log);
    # filter(f_all_critical_events);
    destination(d_audit_parser);
};
