#!/bin/sh

VERSION=1.06
ASTRA_RELEASE=$(lsb_release -rs | cut -b 1-3)

NC='\033[0m' # No Color
Red='\033[0;31m' # Red
Green='\033[0;32m' # Green

all_checks="afick_parms afick_objects"

show_help=false

afick_parms(){
  : '
    Функция проверяет состояние службы afick и код возврата последнего запуска.
    Если служба включена (enabled) и код возврата нулевой, проверка считается успешной
  '
  echo -n "Проверка состояния службы регламентного контроля целостности..."
  result=$(systemctl is-enabled afick 2> /dev/null)
  if [ "$result" != "enabled" ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Служба регламентного контроля целостности не включена"
    if [ ! -f "/etc/systemd/system/afick.service"]; then
      echo "Файл /etc/systemd/system/afick.service отсутствует"
      return 1
    fi
    echo "Выполните команду systemctl enable afick и повторите проверку"
    return 1
  fi

  if [ -z "$(systemctl status afick | grep status=0/SUCCESS)" ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Последний запуск средства регламентного контроля целостности Afick завершен с ошибкой"
    echo "Выполните команду systemctl status afick и проанализируйте логи"
    return 1
  fi
}

afick_objects(){
  echo -n "Проверка настроек средства регламентного контроля целостности..."
  diff $fname /etc/afick.conf &> /dev/null
  if [ $? -ne 0 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Настройки средства регламентного контроля целостности не соответствуют эталонным"
    echo "Сравните файл /etc/afick.conf с эталонным, устраните несоответствия и повторите проверку"
    return 1
  fi
}

if [ "$#" -eq 0 ]; then
  echo "afick-check: Не задан файл с эталонными настройками средства регламентного контроля целостности"
  exit
fi

case $1 in
    -h|--help)
      show_help=true
      ;;
    -v|--version)
      echo afick-check $VERSION
      exit
      ;;
    *)
      fname=$1
      if [ ! -f $fname ]; then
        echo "afick-check:" $fname "Нет такого файла"
        exit
      fi
      ;;
esac

if $show_help; then
  echo "Использование: afick-check -h|-v|ФАЙЛ"
  echo "Проверяет соответствие настроек средства регламентного контроля целостности эталонным, заданным в ФАЙЛе"
  echo
  echo "Аргументы, обязательные для длинных параметров, обязательны и для коротких"
  echo "  -h, --help    показать эту справку и выйти"
  echo "  -v, --version показать информацию о версии и выйти"
  exit
fi

echo $all_checks

for check in $all_checks
  do
    $check
    if [ $? -eq 0 ]; then
      echo -e "${Green}успешно!${NC}"
    fi
  done
