#!/bin/sh
VERSION=1.06
ASTRA_RELEASE=$(lsb_release -rs | cut -b 1-3)
all_checks="audit_parms swapwiper_control secdel_control mac_control \
            nochmodx_lock interpreters_lock macros_lock ptrace_lock sysrq_lock shutdown_lock \
            passwords_policy blocking_policy \
            logrotate_parms parsec_tests afick_parms drweb created_groups created_users"
show_help=false
NC='\033[0m' # No Color
Red='\033[0;31m' # Red
Green='\033[0;32m' # Green

audit_parms() {
  echo -n "Проверка настроек аудита событий..."
  if [ -z "$(useraud -o)" ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Аудит событий не включен"
    return 1
  else
    # Флаги аудита успехов и отказов в шестнадцатеричном представлении
    sucess_events=($(useraud -on | cut -d: -f1))
    fail_events=($(useraud -on | cut -d: -f2))

    if [ $(($sucess_events & $((0x1983f)))) != $((0x1983f)) ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Настройки аудита событий не соответствуют эталону"
      return 1
    fi
    if [ $(($fail_events & $((0x1983f)))) != $((0x1983f)) ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Настройки аудита событий не соответствует эталону"
      return 1
    fi
  fi
  return 0
}

# Далее проверки настроек политик безопасности с помощью инструментов командной строки astra-safepolicy
# см.: https://wiki.astralinux.ru/pages/viewpage.action?pageId=109020865
swapwiper_control() {
  echo -n "Проверка очистки разделов страничного обмена..."
  swapconf=/etc/parsec/swap_wiper.conf
  if [ $ASTRA_RELEASE == "1.6" ]; then
    # Параметр q используется, чтобы ничего не писать в stdout, проверяется только код возврата
    grep -q ENABLED=Y $swapconf
    if [ $? -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Очистка разделов страничного обмена не включена"
      return 1
    fi
  else
    astra-swapwiper-control status
    if [ $? -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Очистка разделов страничного обмена не включена"
      return 1
    fi
  fi

  ignored_part=$(grep IGNORE= $swapconf | cut -d'"' -f2)
    if [ -n "$ignored_part" ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Игнорируется раздел подкачки $ignored_part"
      return 1
    fi
  return 0
}

secdel_control() {
  echo -n "Проверка настроек очистки освобождааемых блоков файловой системы..."
  if [ $ASTRA_RELEASE == "1.6" ]; then
    :
  else
    astra-secdel-control status
      if [ $? -ne 0 ]; then
        echo -e "${Red}ошибка!${NC}"; echo "Очистка освобождаемых блоков файловой системы не включена"
        return 1
      fi
  fi
  # Проверка гарантированного удаления файлов и папок на всех разделах ext!
  while read line; do
    echo $line | grep ext > /dev/null
    if [ $? -eq 0 ]; then
       secdelrnd=$(echo $line | grep -o -E "secdelrnd=[0-9]")
       if [ -z "$secdelrnd" ]; then
         echo -e "${Red}ошибка!${NC}"; echo "Очистка освобождаемых блоков не включена на разделе $(echo $line | cut -d' ' -f1)"
         return 1
       fi
       # TODO Сделать анализ количества проходов случаеного затирания (не менее одного для 1Г и двух для 1В)
    fi
  done < /etc/fstab
  return 0
}

mac_control(){
  echo -n "Проверка режима МРД (мандатного управления доступом)..."
  max_ilev=$(grep -Po 'parsec.max_ilev=\d*' /proc/cmdline | cut -d= -f2)
  if [ $ASTRA_RELEASE == "1.6" ]; then
    if [ -z "$max_ilev" ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Режим МРД не включен"
      return 1
    fi
  else
    astra-mac-control is-enabled
    if [ $? -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Режим МРД не включен!"
      return 1
    fi
  fi

  if [ $max_ilev -eq 0 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Максимально допустимый уровень целостности имеет нулевое значение"
    return 1
  fi
  return 0
}

nochmodx_lock(){
  echo -n "Проверка блокировки установки бита исполнения..."
  if [ $ASTRA_RELEASE == "1.6" ]; then
    if [ $(cat /parsecfs/nochmodx) -eq 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка установки бита исполнения не включена"
      return 1
    fi
  else
    astra-nochmodx-lock is-enabled
    if [ $? -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка установки бита исполнения не включена"
      return 1
    fi
  fi
  return 0
}

interpreters_lock(){
  echo -n "Проверка блокировки интерпретаторов..."
  if [ $ASTRA_RELEASE == "1.6" ]; then
    # Здесь и в аналогичных проверках, если блокировка никогда не включалась возвращается сообщение об ощибке, в стандартный вывод ничего не пишется
    # Если проверяемая блокировка хоть однажды былы включена, то в зависимости от текущей установки возвращается enabled или disabled
    result=$(systemctl is-enabled astra-interpreters-lock 2> /dev/null)
    if [ "$result" != "enabled" ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка интерпретаторов не включена"
      return 1
    fi
  else
    astra-interpreters-lock is-enabled
    if [ $? -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка интерпретаторов не включена"
      return 1
    fi
  fi
  return 0
}

macros_lock(){
  echo -n "Проверка блокировки макросов..."
  if [ $ASTRA_RELEASE == "1.6" ]; then
    result=$(systemctl is-enabled astra-macros-lock 2> /dev/null)
    if [ "$result" != "enabled" ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка макросов не включена"
      return 1
    fi
  else
    astra-macros-lock is-enabled
    if [ $? -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка макросов не включена"
      return 1
    fi
  fi
  return 0
}

ptrace_lock(){
  : '
    Функция проверяет значение вывод команды systemctl is-enabled astra-ptrace-lock (для Astra Linux SE 1.6)
    или  значение, возвращаемое командой astra-ptrace-lock is-enabled (для Astra Linux SE 1.7)
  '
  echo -n "Проверка блокировки трассировки ptrace..."
  if [ $ASTRA_RELEASE == "1.6" ]; then
    result=$(systemctl is-enabled astra-ptrace-lock 2> /dev/null)
    if [ "$result" != "enabled" ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка трассировки ptrace не включена"
      return 1
    fi
  else
    astra-ptrace-lock is-enabled
    if [ $? -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка трассировки ptrace не включена"
      return 1
    fi
  fi
  return 0
}

sysrq_lock(){
  : '
    Функция проверяет значение параметра ядра sysrq (для Astra Linux SE 1.6)
    или  значение, возвращаемое командой astra-sysrq-lock is-enabled (для Astra Linux SE 1.7)
  '
  echo -n "Проверка блокировки клавиш SysRq..."
  if [ $ASTRA_RELEASE == "1.6" ]; then
    if [ $(cat /proc/sys/kernel/sysrq) -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка клавиш SysRq не включена"
      return 1
    fi
  else
    astra-sysrq-lock is-enabled
    if [ $? -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка клавиш SysRq не включена"
      return 1
    fi
  fi
  return 0
}

shutdown_lock(){
  echo -n "Проверка блокировки отключения питания..."
  if [ $ASTRA_RELEASE == "1.6" ]; then
    # TODO Параметр AllowShutdown в секциях [X-:*-Core] и [X-*-Core] (разрешение локального и удаленного выключения питания соответственно)
    # файла /etc/X11/fly-dm/fly-dmcc может принимать значения All, Root или None ("Всем", "Только администратору" или "Никому")
    # В Astra Linux 1.6 astra-shutdown-lock не возвращает некущий статус, только включение или выключени, поэтому парсим вручую
    allow_shutdown=$(python3 -c "import configparser; c = configparser.ConfigParser(); c.read('/etc/X11/fly-dm/fly-dmrc'); print(c['X-*-Core']['AllowShutdown'])")
    if [ $allow_shutdown == "All" ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка отключения питания не включена"
      return 1
    fi
  else
    astra-shutdown-lock is-enabled
    if [ $? -ne 0 ]; then
      echo -e "${Red}ошибка!${NC}"; echo "Блокировка отключения питания не включена"
      return 1
    fi
  fi
  return 0
}

passwords_policy(){
  : '
    Функция проверяет значения параметра PASS_MAX_DAYS в файле /etc/login.defs
    и параметров minlen, lcredit, ucredit и dcredit в файле /etc/pam.d/common-password
    Если параметры PASS_MAX_DAYS имеет значения 90, minlen - значение 8,
    параметры lcredit, ucredit и dcredit имеют ненулевые значения, то проверка считается успешной
  '
  echo -n "Проверка политики паролей..."
  while read line; do
    # NB! В Астре 1.6-10 и 1.7-4 переменные LOGIN_RETRIES и LOGIN_TIMEOUT задаются, но не используются!
    # Можно будет упростить код, здесь оставлено для примера парсинга переменных,
    # задаваемых в формате KEY VALUE (количество пробелов между именем и значением произвольное) по одной в строке
    echo $line | grep -E '^PASS_MAX_DAYS|^LOGIN_RETRIES|^LOGIN_TIMEOUT' > /dev/null
    if [ $? -eq 0 ]; then
      key=$(echo $line | cut -d' '  -f1)
      value=$(echo $line | cut -d' ' -f2)
      declare $key=$value
    fi
  done < /etc/login.defs

  result=0
  if [ $PASS_MAX_DAYS -ne 90 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Максимальное количество дней между сменами пароля задано неверно"
    ((result++))
  fi

  for line in $(grep pam_cracklib.so /etc/pam.d/common-password | awk '{for(i=1;i<=NF;i++) {if(match($i,/=/)) {print $i} } }'); do
    key=$(echo $line | cut -d'='  -f1)
    value=$(echo $line | cut -d'=' -f2)
    declare $key=$value
  done

  # echo $minlen $lcredit $ucredit $dcredit

  if [ $minlen -lt 8 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Требование к минимальной длине пароля задано неверно"
    ((result++))
  fi

  # В этой и последующих проверках значения могут быть не установлены,
  # в этом случае присваиваем им дефолтное значение ноль, а затем проверяем на равенство нулю
  if [ ${lcredit:-0} -eq 0 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Требование к количеству строчных букв в пароле задано неверно"
    ((result++))
  fi

  if [ ${ucredit:-0} -eq 0 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Требование к количеству заглавных букв в пароле задано неверно"
    ((result++))
  fi

  if [ ${dcredit:-0} -eq 0 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Требование к количеству цифр букв в пароле задано неверно"
    ((result++))
  fi

  return $result
}

blocking_policy(){
  : '
    Функция проверяет значения параметров deny и unlock_time в файле /etc/pam.d/common-account
    Если параметры deny и unlock_time равны 3 и 1800 соответственно, то проверка считается успешной
  '
  echo -n "Проверка политики блокировки учетных записей..."
  for line in $(grep pam_tally.so /etc/pam.d/common-account | awk '{for(i=1;i<=NF;i++) {if(match($i,/=/)) {print $i} } }'); do
    key=$(echo $line | cut -d'='  -f1)
    value=$(echo $line | cut -d'=' -f2)
    declare $key=$value
  done
  # echo $deny $unlock_time

  if [ -z "$deny" ] || [ -z "$unlock_time" ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Число неуспешных попыток аутентификации и/или период блокировки не заданы"
    return 1
  fi

  result=0
  if [ $deny -ne 3 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Число неуспешных попыток аутентификации до блокирования учетной записи задано неверно"
    ((result++))
  fi
  if [ $unlock_time -ne 1800 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Период блокировки задан неверно"
    ((result++))
  fi

  # Аналогичный параметр per_user устанавливается в файле /etc/pam.d/common-auth
  if [ -n "$(grep per_user /etc/pam.d/common-account)" ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Назначены индивидуальные настройки параметров блокировки учетных записей"
    ((result++))
  fi

  return $result
}

logrotate_parms(){
  : '
    Функция проверяет наличие в файле /etc/logrotate.conf параметра daily и значение параметра rotate
    если параметр daily задан, а параметр rotate больше или равен 32, то проверка считается успешной
  '
  echo -n "Проверка параметров периодичности ротации журналов регистрации событий..."
  result=0
  if [ -z "$(grep -E '^daily' /etc/logrotate.conf)" ]; then
    ((result++))
  fi

  if [ -z "$(grep -E '^rotate' /etc/logrotate.conf)" ]; then
    ((result++))
  elif [ $(grep -E '^rotate' /etc/logrotate.conf | cut -d" " -f2) -lt 32 ]; then
    ((result++))
  fi

  if [ $result -ne 0 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Параметры периодичности ротации журналов регистрации событий настроены неверно"
    echo "Проверьте файл /etc/logrotate.conf"
  fi
  return $result
}

parsec_tests(){
  echo -n "Проверка установки средств тестирования подсистемы безопасности PARSEC..."
  if [ -z "$(dpkg -l | grep parsec-tests)" ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Средства тестирования подсистемы безопасности PARSEC не установлены"
    return 1
  fi
}

afick_parms(){
  : '
    Функция проверяет состояние службы afick и код возврата последнего запуска.
    Если служба включена (enabled) и код возврата нулевой, проверка считается успешной
  '
  echo -n "Проверка настроек средства регламентного контроля целостности Afick..."
  result=$(systemctl is-enabled afick 2> /dev/null)
  if [ "$result" != "enabled" ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Служба запуска средства регламентного контроля целостности Afick не включена"
    return 1
  fi

  if [ -z "$(systemctl status afick | grep status=0/SUCCESS)" ]; then
    echo "Последний запуск средства регламентного контроля целостности Afick завершен с ошибкой!"
    echo "Выполните команду systemctl status afick и проанализируйте логи"
    return 1
  fi
}

drweb(){
  : '
    Функция проверяет список запущенных компонентов САВЗ Dr.Web и выполняет попытку создания тестового вируса eicar.
    Если компоненты ConfigD, ScanEngine, FileCheck и LinuxSpider запущены,
    тестовый вирус eicar обнаружен и помещен в карантин, проверка считается успешной
  '
  echo -n "Проверка работоспособности САВЗ Dr.Web..."
  if [ $(drweb-ctl appinfo | awk '{print $1 $3}' | grep -c -E "ConfigD;RUNNING|ScanEngine;RUNNING|FileCheck;RUNNING|LinuxSpider;RUNNING") -ne 4 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Запущены не все компоненты САВЗ Dr.Web"
    return 1
  fi
  drweb-ctl quarantine --Delete All 1> /dev/null
  grep X5O /opt/drweb.com/share/doc/drweb-se/readme.eicar > /tmp/eicar

  # На всякий случай ждем 5 сек для обнаружения тестового вируса и помещения его в карантин
  sleep 5
  if [ -z "$(drweb-ctl quarantine)" ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Тестовый вирус eicar не обнаружен"
    return 1
  fi
}

created_groups(){
  echo -n "Проверка групп пользователей, созданных после установки системы..."
  getent group | awk -F: '{ if ($3 >= 1000 && $3 < 60000) printf " %s", $1}'; echo
}

created_users(){
# Сравнение эталонных настроек учетных записей пользователей, сохраненных в файле users.lst, с текущими настройками:
echo -n "Проверка учетных записей пользователей, созданных после установки системы..."
# Учетные записи сортируются в алфавитном порядке, т.к. важен не порядок их создания, а само наличие и правильные настройки
# В дополнение к оболочке /bin/bash проверяем /bin/sh, т.к. в некоторых случаях может быть установлена она
diff=$(getent passwd | sort | awk -F: '{if (match($NF, "/bin/(ba)?sh")) { system("groups " $1); system("pdpl-user " $1)}}' | diff -y - users.lst)
if [ $? -ne 0 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Настройки учетных записей пользователей не соответствуют эталонным"
    getent passwd | sort | awk -F: '{if ($NF=="/bin/bash") { system("groups " $1); system("pdpl-user " $1)}}' | diff -y - users.lst
    # echo $diff
    return 1
fi
}

while [[ "$#" -gt 0 ]]; do
  case $1 in
    -l|--list)
      echo $all_checks
      exit
      ;;
    -h|--help)
      show_help=true
      ;;
    -v|--version)
      echo autocheck $VERSION
      exit
      ;;
    *)
      # Проверка, что перед $1 идет начало строки или пробел, а после - пробел или конец строки
      # Необходимо, чтобы агрумент в точности совпадал с именем проверки, а не являлся подстрокой
      if [ -n "$(echo $all_checks | grep -E "(^| )$1( |$)")" ]; then
          selected_checks="$selected_checks $1"
        else
          echo "Неизвестный параметр или проверка $1"
          exit
      fi
      ;;
  esac
  shift
done

if [ -z "$selected_checks" ]; then
  selected_checks=$all_checks
fi

if $show_help; then
  echo "Использование: autocheck [-l|-h|-v] [ПРОВЕРКА]..."
  echo "Программа автоматизированной проверки настроек комплекса средств защиты информации"
  echo
  echo "Аргументы, обязательные для длинных параметров, обязательны и для коротких"
  echo "  -l, --list    показать список проверок и выйти"
  echo "  -h, --help    показать эту справку и выйти"
  echo "  -v, --version показать информацию о версии и выйти"
  echo "Если ПРОВЕРКА не задана, выполняются все проверки"
  exit
fi

for check in $selected_checks
  do
    $check
    if [ $? -eq 0 ]; then
      echo -e "${Green}успешно!${NC}"
    fi
  done

exit
