#!/bin/sh

VERSION=1.06
ASTRA_RELEASE=$(lsb_release -rs | cut -b 1-3)

NC='\033[0m' # No Color
Red='\033[0;31m' # Red
Green='\033[0;32m' # Green

all_checks="running_components virus_detection"

show_help=false

running_components(){
  : '
    Функция проверяет список запущенных компонентов САВЗ Dr.Web и выполняет попытку создания тестового вируса eicar.
    Если компоненты ConfigD, ScanEngine, FileCheck и LinuxSpider запущены,
    тестовый вирус eicar обнаружен и помещен в карантин, проверка считается успешной
  '
  echo -n "Проверка работоспособности САВЗ Dr.Web..."
  if [ $(drweb-ctl appinfo | awk '{print $1 $3}' | grep -c -E "ConfigD;RUNNING|ScanEngine;RUNNING|FileCheck;RUNNING|LinuxSpider;RUNNING") -ne 4 ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Запущены не все компоненты САВЗ Dr.Web"
    return 1
  fi
}

virus_detection(){
  echo -n "Проверка обнаружения тестового вируса eicar..."
  drweb-ctl quarantine --Delete All 1> /dev/null
  grep X5O /opt/drweb.com/share/doc/drweb-se/readme.eicar > /tmp/eicar

  # На всякий случай ждем 5 сек для обнаружения тестового вируса и помещения его в карантин
  sleep 5
  if [ -z "$(drweb-ctl quarantine)" ]; then
    echo -e "${Red}ошибка!${NC}"; echo "Тестовый вирус eicar не обнаружен"
    return 1
  fi
}

while [[ "$#" -gt 0 ]]; do
  case $1 in
    -l|--list)
      echo $all_checks
      exit
      ;;
    -h|--help)
      show_help=true
      ;;
    -v|--version)
      echo drweb-check $VERSION
      exit
      ;;
    *)
      # Проверка, что перед $1 идет начало строки или пробел, а после - пробел или конец строки
      # Необходимо, чтобы агрумент в точности совпадал с именем проверки, а не являлся подстрокой
      if [ -n "$(echo $all_checks | grep -E "(^| )$1( |$)")" ]; then
          selected_checks="$selected_checks $1"
        else
          echo "Неизвестный параметр или проверка $1"
          exit
      fi
      ;;
  esac
  shift
done

if [ -z "$selected_checks" ]; then
  selected_checks=$all_checks
fi

if $show_help; then
  echo "Использование: drweb-check [-l|-h|-v] [ПРОВЕРКА]..."
  echo "Проверяет настройки комплекса средств защиты информации ОС Astra Linux SE"
  echo
  echo "Аргументы, обязательные для длинных параметров, обязательны и для коротких"
  echo "  -l, --list    показать список проверок и выйти"
  echo "  -h, --help    показать эту справку и выйти"
  echo "  -v, --version показать информацию о версии и выйти"
  echo "Если ПРОВЕРКА не задана, выполняются все проверки"
  exit
fi

for check in $selected_checks
  do
    $check
    if [ $? -eq 0 ]; then
      echo -e "${Green}успешно!${NC}"
    fi
  done

exit
